name: Deploy Vulnerable Application                                  # workflow name

on:
  pull_request:
    branches:
      - master
jobs:
  security:
    name: deploy-sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SYNK_API_KEY }}
        with:
          json: true
          args: --file=package.json
      - uses: garethr/snyk-to-sarif@master
      - uses: actions/upload-artifact@v2
        name: SARIF
        with:
          path: snyk.sarif        
      # - name: Sarif File
      #   uses: snyk/actions/node@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SYNK_API_KEY }}
      #   with:      
      #       args: --sarif-file-output=snyk.sarif 
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://hackademyappinsecure.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  deploy-heroku:
    name: Deploy-Heroku
    runs-on: ubuntu-latest
    needs: [security, zap_scan]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hackademyappinsecure" #Must be unique in Heroku
          heroku_email: "ricardo.almario@gmail.com"
          remote_branch: "master"
          usedocker: true
        